### ISSUE TITLE
TelegramBot object has no attribute 'allowed_users' [RUS]

### ISSUE THREAD

**Issue by theonedemon** [idlesign/torrt#39]
Добрый день, решил попробовать новую фичу, но не получается настроить:
```
torrt configure_bot telegram token=12345677:SDFDFSDFSDF allowed_users=111111111
```
получаю ошибку:
```
Traceback (most recent call last):
  File "/usr/local/bin/torrt", line 10, in <module>
    sys.exit(process_commands())
  File "/usr/local/lib/python3.5/dist-packages/torrt/main.py", line 224, in process_commands
    configure_bot(args['bot_alias'], settings_dict_from_list(args['settings']))
  File "/usr/local/lib/python3.5/dist-packages/torrt/toolbox.py", line 84, in configure_bot
    return configure_entity('Bot', BotClassesRegistry, bot_alias, settings_dict)
  File "/usr/local/lib/python3.5/dist-packages/torrt/utils.py", line 93, in configure_entity
    obj.save_settings()
  File "/usr/local/lib/python3.5/dist-packages/torrt/utils.py", line 365, in save_settings
    settings[name] = getattr(self, name)
AttributeError: 'TelegramBot' object has no attribute 'allowed_users'
```

Python 3.5.3
torrt==0.11.1
python-telegram-bot==11.1.0

**Comment by idlesign** [comment]
Доброго дня,
Можно попробовать `master`. Версия с ним ещё не выпущена.

**Comment by theonedemon** [comment]
Спасибо собрал из ветки `master` и смог сконфигурировать.
теперь в чате с ботом выполняю /list и ловлю такие ошибки в обработчике `torrt run_bots`:
```
WARNING: A TelegramError was raised while processing the Update
ERROR: No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 203, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.5/dist-packages/torrt-0.11.1-py3.5.egg/torrt/bots/telegram_bot.py", line 82, in handle_callbacks
    handler(bot, update.callback_query)
  File "/usr/local/lib/python3.5/dist-packages/torrt-0.11.1-py3.5.egg/torrt/bots/telegram_bot.py", line 203, in command_list_torrents
    update.message.reply_text('{}. {}'.format(i, trnt['name']))
  File "/usr/local/lib/python3.5/dist-packages/telegram/message.py", line 455, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 205, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out

````
у меня зарегистрировано 10 торрентов и смущает, что  каждый из них приходит отдельным сообщением:
```
mi_mini, [31.03.19 16:34]
[В ответ на mi_mini]
1. Les.Miserables.S01.WEB-DL.1080p.Rus.Eng
.....
mi_mini, [31.03.19 16:34]
[В ответ на mi_mini]
5. The.Rookie.S01.WEBRip.720p
.....
mi_mini, [31.03.19 16:34]
[В ответ на mi_mini]
6. The_Big_Bang_Theory_(s12)_1080p_KB
```

**Comment by idlesign** [comment]
А телеграм вообще доступен из этой сети?
        20:39, 31 марта 2019 г., theonedemon <notifications@github.com>:Спасибо собрал из ветки master и смог сконфигурировать.
теперь в чате с ботом выполняю /list и ловлю такие ошибки в обработчике torrt run_bots:
WARNING: A TelegramError was raised while processing the Update
ERROR: No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 203, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/usr/local/lib/python3.5/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.5/dist-packages/torrt-0.11.1-py3.5.egg/torrt/bots/telegram_bot.py", line 82, in handle_callbacks
    handler(bot, update.callback_query)
  File "/usr/local/lib/python3.5/dist-packages/torrt-0.11.1-py3.5.egg/torrt/bots/telegram_bot.py", line 203, in command_list_torrents
    update.message.reply_text('{}. {}'.format(i, trnt['name']))
  File "/usr/local/lib/python3.5/dist-packages/telegram/message.py", line 455, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 205, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out


у меня зарегистрировано 10 торрентов и смущает, что  каждый из них приходит отдельным сообщением:
mi_mini, [31.03.19 16:34]
[В ответ на mi_mini]
1. Les.Miserables.S01.WEB-DL.1080p.Rus.Eng
.....
mi_mini, [31.03.19 16:34]
[В ответ на mi_mini]
5. The.Rookie.S01.WEBRip.720p
.....
mi_mini, [31.03.19 16:34]
[В ответ на mi_mini]
6. The_Big_Bang_Theory_(s12)_1080p_KB

**Comment by theonedemon** [comment]
> А телеграм вообще доступен из этой сети?
не совсем понял вопроса, сам сервис да доступен, без впн и прокси

**Comment by idlesign** [comment]
@toshka, прокомментируй, пожалуйста, если есть соображения.

**Comment by toshka** [comment]
Очень похоже на сетевую проблему. Вероятно, скрипт не всегда может достучаться до телеграма и обратно. Что касается лимитов, то при 10 раздачах в лимит упереться можно, если запросить несколько раз подряд /list. В доке написано расплывчато, но может быть ограничение уже на 20 сообщаниях в минуту.
Я изначально хотел сделать одним сообщением, но для восприятия ответа удобнее оказалось разбить его по раздачам. Тем не менее, если есть такие проблемы, то я могу объединить обратно.

@theonedemon  прошу прощения за allowed_users, накосячил в прошлой версии.

**Comment by theonedemon** [comment]
стянул обнову с мастера всё супер, ошибок нет.
Спасибо!
