### ISSUE TITLE
qbittorrent remove torrent bug. [RUS]

### ISSUE THREAD

**Issue by malef1k** [idlesign/torrt#72]
Возвращаясь опять к qbittorrent. командой walk торренты обновляет, то не удаляет старые.
Также новый добавленный торрент не добавляется в список зарегестрированных (в torrt list его нет)

**Логи при обновлении.**

INFO: Torrent walk is triggered
INFO: Torrent walk is started
INFO: Getting torrents from `qbittorrent` ...
INFO:   Processing `Foundation.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DoVi.by.DVT`...
INFO:     Torrent is updated
ERROR: QBittorrentRPC: Failed to query RPC `http://127.0.0.1:8085/api/v2/torrents/delete`: Bad Request
ERROR: QBittorrentRPC: Failed to query RPC `rem_torrent`: Bad Request
ERROR: Walk failed. Reason: Bad Request
INFO: Torrent walk is finished

**Логи если попытаться удалить какой либо из торрентов.**

~# /var/packages/py3k/target/usr/local/bin/torrt remove_torrent 548a334b9604bd1de1c9aec800ff9133c71b2e0b
INFO: Removing torrent `548a334b9604bd1de1c9aec800ff9133c71b2e0b` (with data = False) ...
INFO: Removing torrent using `qbittorrent` RPC ...
ERROR: QBittorrentRPC: Failed to query RPC `http://127.0.0.1:8085/api/v2/torrents/delete`: Bad Request
ERROR: QBittorrentRPC: Failed to query RPC `rem_torrent`: Bad Request
Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/torrt/rpc/qbittorrent.py", line 118, in query
    raise QBittorrentRPCException(response.text.strip() or response.reason)
torrt.rpc.qbittorrent.QBittorrentRPCException: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/torrt/rpc/qbittorrent.py", line 123, in query
    raise QBittorrentRPCException(f'{e}')
torrt.rpc.qbittorrent.QBittorrentRPCException: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/bin/torrt", line 8, in <module>
    sys.exit(process_commands())
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/torrt/main.py", line 206, in process_commands
    remove_torrent(args['hash'], args['delete_data'])
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/torrt/toolbox.py", line 256, in remove_torrent
    rpc_object.method_remove_torrent(hash_str, with_data=with_data)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/torrt/rpc/qbittorrent.py", line 192, in method_remove_torrent
    return self.auth_query(self.build_params('rem_torrent', {'data': data}))
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/torrt/rpc/qbittorrent.py", line 137, in auth_query
    return self.query(data, files)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/torrt/rpc/qbittorrent.py", line 128, in query
    raise QBittorrentRPCException(f'{e}')
torrt.rpc.qbittorrent.QBittorrentRPCException: Bad Request

**Comment by idlesign** [comment]
Спасибо.
На неделе погляжу, что там ещё не так.

**Comment by idlesign** [comment]
> curl "http://localhost:8085/api/v2/torrents/delete?hashes=64308f968dcfd1410f6531a08e902f74cfe73077&deleteFiles=false" --cookie "SID=LUNypb+uoJgAv00mm6FDWZMLoy29WHhW"
> И все удаляется

Отлично, спасибо. 
А теперь, что будет, если этот же запрос, только не GET, а POST, что-то вроде

```
curl -d "hashes=64308f968dcfd1410f6531a08e902f74cfe73077&deleteFiles=false" -X POST http://localhost:8085/api/v2/torrents/delete --cookie "SID=LUNypb+uoJgAv00mm6FDWZMLoy29WHhW"
```
