### ISSUE TITLE
Ошибка при обновлении торрента с rutracker в qbittorrent

### ISSUE THREAD

**Issue by MaksimShakavin** [idlesign/torrt#86]
Текст ошибки:
```
Traceback (most recent call last):
  File "/usr/local/bin/torrt", line 8, in <module>
    sys.exit(process_commands())
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torrt/main.py", line 197, in process_commands
    walk(forced=args['forced'], silent=True)
  File "/usr/local/lib/python3.11/site-packages/torrt/toolbox.py", line 324, in walk
    updated = update_torrents(cfg['torrents'], remove_outdated=remove_outdated)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torrt/toolbox.py", line 402, in update_torrents
    raw_last_updated = torrents[rpc_torrent['hash']]['page']['date_updated']
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'date_updated'
```
в клиенте только один торрент и только один торрент добавлен в torrt

**Comment by idlesign** [comment]
Спасибо за информацию.
А это версия из pypi или из мастер-ветки?

**Comment by MaksimShakavin** [comment]
Из мастер ветки

**Comment by idlesign** [comment]
Понял, спасибо. Попробую на этой неделе глянуть, что мы там наворотили.

**Comment by idlesign** [comment]
Чуть скорректировал код. Можно попробовать из мастера.
